project:
  type: book
  output-dir: docs

book:
  title: "Lego I"
  author: Felipe Lamarca
  chapters:
    - index.qmd
    - part: Aulas
      chapters:
        - aulas/aula-1.qmd
        - aulas/aula-2.qmd
        - aulas/aula-5.qmd
        - aulas/aula-6.qmd
        - aulas/aula-7.qmd
        - aulas/aula-8.qmd
    - part: Listas
      chapters:
        - listas/nivelamento/lista-nivelamento.qmd
        - listas/lista-1/lista1.qmd
        - listas/lista-2/lista2.qmd
format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



